local mark = require("harpoon.mark")
local ui = require("harpoon.ui")

vim.keymap.set("n", "<leader>a", mark.add_file, { desc = "Add Harpoon file" })
vim.keymap.set("n", "<leader>h", ui.toggle_quick_menu, { desc = "Toggle Harpoon" })
vim.keymap.set("n", "<C-j>", function()
	ui.nav_file(1)
end, { desc = "Go to Harpoon 1" })
vim.keymap.set("n", "<C-m>", function()
	ui.nav_file(2)
end, { desc = "Go to Harpoon 2" })
vim.keymap.set("n", "<C-i>", function()
	ui.nav_file(3)
end, { desc = "Go to Harpoon 3" })
vim.keymap.set("n", "<C-k>", function()
	ui.nav_file(4)
end, { desc = "Go to Harpoon 4" })
